
global:                            
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rules.yml"
  # - "first.rules"
  # - "second.rules"

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: ['prometheus1.ordix.de:9093']

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['prometheus1.ordix.de:9090']

#  - job_name: 'node_exporter'
#    static_configs:
#      - targets: ['prometheus1.ordix.de:9100','prometheus2.ordix.de:9100']
#        labels:
#          group: 'production'
#
#  - job_name: 'process-exporter'
#    static_configs:
#      - targets:
#          - 'prometheus1.ordix.de:9256'
#          - 'prometheus2.ordix.de:9256'
#        labels:
#          group: 'production'

  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9104']

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://www.ordix.de
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus1.ordix.de:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scheme: https
    metrics_path: /node-exporter/metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['prometheus1.ordix.de:9443','prometheus2.ordix.de:9443']

  - job_name: 'process-exporter'
    scrape_interval: 5s
    scheme: https
    metrics_path: /process-exporter/metrics
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: ordix
      password: ordix
    static_configs:
      - targets:
          - prometheus1.ordix.de:9443
          - prometheus2.ordix.de:9443

    relabel_configs:
      - source_labels: [__scheme__]
        target_label: http_schema
